name: Python Application CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build essentials
      run: |
        python -m pip install --upgrade pip
        pip install setuptools==57.5.0 wheel==0.37.1 cython==0.29.24
    - name: Install core dependencies
      run: |
        pip install "numpy>=1.24.0,<1.25.0"
        pip install "pandas>=1.4.0,<1.5.0"
        pip install "pydantic>=1.9.0,<2.0.0"
    - name: Install other dependencies
      run: |
        pip install -r requirements.txt --no-deps
        pip install --no-deps "scikit-learn>=1.0.2"
        pip install --no-deps "spacy>=3.2.0,<3.3.0"
    - name: Download spacy model
      run: python -m spacy download en_core_web_sm
    - name: Run tests
      run: pytest
